from pydantic import BaseModel, Field
from datetime import datetime
from typing import Optional, List


# --- Model Schemas ---
class ModelBase(BaseModel):
    name: str
    normalized_name: str
    popularity: Optional[int] = None
    versatility: Optional[int] = None
    longevity: Optional[int] = None
    industry_impact: Optional[int] = None
    fan_appeal: Optional[int] = None

class ModelCreate(BaseModel):
    name: str
    # normalized_name will be generated by the service
    popularity: Optional[int] = Field(None, ge=1, le=10)
    versatility: Optional[int] = Field(None, ge=1, le=10)
    longevity: Optional[int] = Field(None, ge=1, le=10)
    industry_impact: Optional[int] = Field(None, ge=1, le=10)
    fan_appeal: Optional[int] = Field(None, ge=1, le=10)

class ModelUpdate(BaseModel):
    name: Optional[str] = None
    normalized_name: Optional[str] = None # Should probably be handled internally
    popularity: Optional[int] = Field(None, ge=1, le=10)
    versatility: Optional[int] = Field(None, ge=1, le=10)
    longevity: Optional[int] = Field(None, ge=1, le=10)
    industry_impact: Optional[int] = Field(None, ge=1, le=10)
    fan_appeal: Optional[int] = Field(None, ge=1, le=10)

class ModelResponse(ModelBase):
    id: int

    class Config:
        from_attributes = True # Allow ORM models to be converted to Pydantic models


# --- Media Schemas ---
class MediaBase(BaseModel):
    model_id: int
    file_path: str
    media_type: str
    created_at: datetime
    last_sent_at: Optional[datetime] = None
    rating: Optional[int] = None
    rating_caption: Optional[str] = None
    rated_at: Optional[datetime] = None

class MediaCreate(BaseModel):
    model_name: str # Use model name for creation, service resolves to id
    file_id: str # Telegram file_id, used for actual file download
    unique_id: str # Telegram file_unique_id, used for filename
    media_type: str

class MediaResponse(MediaBase):
    id: int

    class Config:
        from_attributes = True

